config/routes.rb
Rails.application.routes.draw do
  # namespace :dashboard do
  #   get 'dashboard/index'
  # end
  devise_for :librarians
  devise_for :middlemen

  root to: redirect('/books')

  get 'books', to: 'pages#index'
  get 'books/new', to: 'pages#index'
  get 'books/:id', to: 'pages#index'
  get 'books/:id/edit', to: 'pages#index'


  namespace :api do

    # authenticated :librarian do
    #     resources :books, module: "librarian", :only => [:show, :index]
    # end

    # authenticated :middleman do
    #     resources :books, module: "middleman"
    # end
    resources :books do
      get :manage, on: :collection
    end

  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :address, as: :addressable
  alias_method :location, :address
end

app/models/depot.rb
class Depot < ApplicationRecord
  has_one :address, as: :addresssable, dependent: :destroy
end

app/models/librarian.rb
class Librarian < User
  has_one :address, as: :addressable
  has_many :books, foreign_key: 'user_id', dependent: :destroy
end

app/models/middleman.rb
class Middleman < User
  has_one :address, as: :addressable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  before_action :find_book, only: [ :show, :update, :destroy]
  respond_to :json

  def index
    respond_with current_user.books.order(created_at: :DESC)
  end

  def show
    respond_with @book
  end

  def create
    respond_with Book, json: current_user.books.create(book_params)
  end

  def destroy
    respond_with @book.destroy
  end

  def update
    respond_with Book, json: @book.update(book_params)
  end

  private

  def find_book
    @book ||= current_user.books.find(params[:id])
  end


  def book_params
    params.require(:book).permit(
      :id,
      :title,
      :description
    )
  end
end

app/controllers/api/dashboard_controller.rb
class Api::DashboardController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Note order of array defines redirect paths
  devise_group :user, contains: [:librarian, :middleman]
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/dashboard/index.html.erb
<h1>Dashboard::Dashboard#index</h1>
<p>Find me in app/views/dashboard/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <nav>
      Navigation
      <% if middleman_signed_in? %>
        <%= button_to 'Log out', destroy_middleman_session_path, method: :delete %>
      <% end %>
      <% if librarian_signed_in? %>
        <%= button_to 'Log out', destroy_librarian_session_path, method: :delete %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div id="root"></div>